[project]
name = "wormenpracticum"
version = "0.0.1"
description = "Python rewrite of the UvA Psychobiologie wormenpracticum."
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "nidaqmx>=1.4.1",
    "numpy>=2.4.2",
    "pandas>=3.0.1",
    "pyqtgraph>=0.14.0",
    "pyside6>=6.11.0",
    "scipy>=1.17.1",
]

[dependency-groups]
dev = [
    "pyinstaller>=6.19.0",
    "pytest>=9.0.2",
    "ruff>=0.15.2",
]

[tool.ruff]
exclude = [
    "app/window/",
    "legacy",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
